### ISSUE TITLE
Q: standard channels vs use std::comm::{channel, Sender, Receiver}; 

### ISSUE THREAD

**Issue by diasdavid** [steveklabnik/rust_for_rubyists#112]
Hi @steveklabnik ! 

Thank you for full day of Rust last week! I was just going through your http://www.rustforrubyists.com/ (although I never did Ruby myself :D ) and got confused on the tasks chapter, precisely when you say:

`This is really only one-way transit, though: what if we want to communicate back and forth? Setting up two ports and channels each time would be pretty annoying, so we have some standard library code for this.` 

And solve the problem by creating two `pipes` again:

```rust
    let (fromParentSender, fromParentReceiver) = channel();
    let (fromChildSender, fromChildReceiver) = channel();
```

What's is the gain by using the `std::comm::{channel, Sender, Receiver}; `, seems like a the same `let (chan, port) = channel();` 

Thank you!

**Comment by steveklabnik** [comment]
Now that r4r is deprecated, this will not be fixed

**Comment by tak1n** [comment]
Just wanted to say thank you for this great guide 
It was the first contact I had with rust.

And also thx for your great effort on documenting rust :)

**Comment by steveklabnik** [comment]
You're very welcome 😄
