### ISSUE TITLE
spawn is not a valid command

### ISSUE THREAD

**Issue by kevinburke** [steveklabnik/rust_for_rubyists#122]
using the january 14 nightly, I am getting <code>error: unresolved name `spawn`. Did you mean \`host\`?</code>

Chapter 6 still refers to `spawn` often.

**Comment by steveklabnik** [comment]
Yes, Rust for Rubyists tracks the last release, which is 0.12.0. Since then, `spawn` has been removed from the preude, and is now `std::thread::Thread::spawn`.

**Comment by kevinburke** [comment]
Ah - I didn't realize it tracks released versions and not the nightly.


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by steveklabnik** [comment]
Now that r4r is deprecated, this will not be fixed

**Comment by WindOfNightRain** [comment]
in verson 1.7.0, use std::thread::spawn
