### ISSUE TITLE
Mac OS X 10.11 El Capitan makes LaTeX installation more difficult

### ISSUE THREAD

**Issue by skunkworker** [steveklabnik/rust_for_rubyists#127]
Earlier tonight I installed mactex on Mac OS X 10.11 and got the book compiled, but it took a number of steps that I didn't immediately foresee. Because the default location of installations has changed in 10.11, you have to manually tell pandoc where the pdflatex engine is now.

So here are the commands that it took for me to get it working properly.
`$ brew install pandoc`
`$ brew install homebrew/binary/kindlegen` if you need it
`$ brew install Caskroom/cask/mactex` this will take awhile
 
and adding the latex-engine to a modified makefile made it work.
I'll be honest, I may have missed one install, but for the most part this should help speed it up.

```
rust-for-rubyists.epub: $(ALL_FILES)
	pandoc --latex-engine=/Library/TeX/Root/bin/x86_64-darwin/pdflatex $(EPUB_OPTS) -o $@ $(CONTENTS)

rust-for-rubyists.pdf: $(ALL_FILES)
	pandoc --latex-engine=/Library/TeX/Root/bin/x86_64-darwin/pdflatex $(EPUB_OPTS) -o $@ $(CONTENTS)

rust-for-rubyists.mobi: rust-for-rubyists.epub
	kindlegen rust-for-rubyists.epub

book/book.html: $(CHAPTERS)
	pandoc --latex-engine=/Library/TeX/Root/bin/x86_64-darwin/pdflatex -o $@ $(HTML_OPTS) $(CHAPTERS)

book/%.html : book/%.md
	pandoc --latex-engine=/Library/TeX/Root/bin/x86_64-darwin/pdflatex -o $@ $(HTML_OPTS) $<
```
Here is a gist with the changes:
https://gist.github.com/skunkworker/1e215a9a28d235d35086

**Comment by steveklabnik** [comment]
Thanks! This repository is pretty much deprecated, but if you send me a PR for this, I'll merge it.

**Comment by skunkworker** [comment]
It turns out this may not be necessary, as I didn't reboot after installing LaTeX and the other libraries, and once I did pandoc had no issues.
