### ISSUE TITLE
cannot find type `int` in this scope

### ISSUE THREAD

**Issue by szTheory** [steveklabnik/rust_for_rubyists#131]
```rust
fn div_by_three(num: int) -> bool { false
}
```

Was giving me this error

```
error[E0412]: cannot find type `int` in this scope
 --> src/main.rs:1:22
  |
1 | fn div_by_three(num: int) -> bool {
  |                      ^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0412`.
error: Could not compile `rusthelloworld`.
```

I had to switch it from `int` to `i64` to get example working

```
➜ rustc --version
rustc 1.38.0 (625451e37 2019-09-23)
```

Figured easier to open an issue than try to correct the example code with a PR since I am learning, and do not know, Rust.

**Comment by steveklabnik** [comment]
Hi! This book is *very* out of date; I stopped updating it well before Rust 1.0, which means that the code will not work with today's Rust.

This eventually became https://doc.rust-lang.org/stable/book/; I recommend reading that instead!
