### ISSUE TITLE
Long code lines are either cut off or wrapped weirdly

### ISSUE THREAD

**Issue by carols10cents** [steveklabnik/rust_for_rubyists#67]
In the PDF version, any line of code longer than about 92 chars just gets cut off:

![screen shot 2014-05-03 at 9 23 42 pm](https://cloud.githubusercontent.com/assets/193874/2871845/bff7deb8-d32a-11e3-9ac7-9983e434518a.png)

Online, at about 95 chars, the line gets wrapped, sometimes in the middle of words:

![screen shot 2014-05-03 at 9 25 00 pm](https://cloud.githubusercontent.com/assets/193874/2871848/effa9f42-d32a-11e3-9298-1482174ed5fd.png)

Same deal in the .mobi version in the amazon kindle for mac app:

![screen shot 2014-05-03 at 9 36 45 pm](https://cloud.githubusercontent.com/assets/193874/2871875/aab2665c-d32c-11e3-8bc8-d3c12c87832c.png)

The epub in iBooks on OSX seems to wrap ok.

I don't know whether you'd want to try making these lines shorter or making the different formats wrap correctly or if that's even possible :-/ Computers :sob:

**Comment by steveklabnik** [comment]
Now that r4r is deprecated, this will not be fixed
